

import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className="min-h-screen">
      <Head>
        <title>Code Projekt</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Navbar */}
      <nav className={`flex items-center justify-between p-4 text-white ${styles.navbar}`}>

        <div className="flex items-center space-x-2">
          <Image src="/logo-imageV4white.png" alt="Logo" width={115} height={160} />
        </div>

        <div className="flex items-center space-x-11 ">
          <a href="#" className="hover:underline">DIAMOND PACKS</a>
          <a href="#" className="hover:underline">EVENT PRE-ORDER</a>
          <a href="#" className="hover:underline">REDEEM CODE</a>
          <a href="#" className="hover:underline">ESPORTS</a>
          <a href="#" className="hover:underline">MERCH</a>
          <a href="#" className="hover:underline">MORE</a>
        </div>

        <div className="flex items-center space-x-2">
          <input type="text" placeholder="search here" className={`px-2 py-1 rounded-lg ${styles.navbar_search}`} />
          <Image src="/profile-image.png" alt="Circle Image" width={35} height={50} className="rounded-full" />
          <button className="bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded">
            sign in/name
          </button>
        </div>
      </nav>

      {/* Hero Section */}
      <section className={`relative m-20 mt-8 mb-0 ${styles.hero}`} style={{ height: '50vh' }}>
        <Image src="/hero-imageMain.jpg" alt="Hero Image" layout="fill" />
        <div className="absolute inset-0 flex items-end justify-center pb-16">
          <div className="text-center">
            <h1 className="text-4xl font-bold text-white">PRESENT EVENT NAME</h1>
            <button className={`mt-4 ${styles['custom-button']}`}>
              BUY DIAMONDS
            </button>
          </div>
        </div>
      </section>

      {/* Menu Section */}
      <section className="grid grid-cols-4 gap-4 p-20 pt-16" >
        <div className="relative" style={{ height: '65vh' }}>
          <Image src="/menu-imageV2.png" alt="Menu Item 1" layout="fill" />
          <div className="absolute inset-0 flex items-center justify-center">
            
          </div>
        </div>
        <div className="relative" style={{ height: '65vh' }}>
          <Image src="/menu-imageV2.png" alt="Menu Item 2" layout="fill" />
          <div className="absolute inset-0 flex items-center justify-center">
            <h2 className="text-2xl text-white">COMING SOON</h2>
          </div>
        </div>
        <div className="relative" style={{ height: '65vh' }}>
          <Image src="/menu-imageV2.png" alt="Menu Item 3" layout="fill" />
          <div className="absolute inset-0 flex items-center justify-center">
            <h2 className="text-2xl text-white">COMING SOON</h2>
          </div>
        </div>
        <div className="relative" style={{ height: '65vh' }}>
          <Image src="/menu-imageV2.png" alt="Menu Item 4" layout="fill" />
          <div className="absolute inset-0 flex items-center justify-center">
            <h2 className="text-2xl text-white">COMING SOON</h2>
          </div>
        </div>
      </section>
    </div>
  );
}